default_language_version:
  python: python3.10
repos:
  - repo: 'https://github.com/pycqa/bandit'
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - '-iii'
          - '-ll'
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: 'https://github.com/ambv/black'
    rev: 22.3.0
    hooks:
      - id: black